<template>
  <div class="terms-page pb-5">

    <div class="bg-body-tertiary border-bottom py-5 mb-5">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-8">
            <h1 class="display-5 fw-bold mb-2">Terms of Service</h1>
            <p class="lead text-muted mb-0">
              Please read these terms carefully before using Anonymous Talk.
            </p>
          </div>
          <div class="col-lg-4 text-lg-end mt-3 mt-lg-0">
            <span class="badge bg-secondary-subtle text-secondary border px-3 py-2 rounded-pill">
              Last Updated: {{ lastUpdated }}
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row g-5">

        <div class="col-lg-3 d-none d-lg-block">
          <div class="sticky-top" style="top: 2rem; z-index: 1;">
            <h6 class="fw-bold text-uppercase text-muted small mb-3 ls-1">Agreement</h6>
            <div class="list-group list-group-flush border-start">
              <a href="#acceptance" class="list-group-item list-group-item-action bg-transparent border-0 py-2 ps-3 text-secondary" @click.prevent="scrollTo('acceptance')">1. Acceptance</a>
              <a href="#accounts" class="list-group-item list-group-item-action bg-transparent border-0 py-2 ps-3 text-secondary" @click.prevent="scrollTo('accounts')">2. Accounts & Identity</a>
              <a href="#trust" class="list-group-item list-group-item-action bg-transparent border-0 py-2 ps-3 text-secondary" @click.prevent="scrollTo('trust')">3. Trust Score System</a>
              <a href="#content" class="list-group-item list-group-item-action bg-transparent border-0 py-2 ps-3 text-secondary" @click.prevent="scrollTo('content')">4. User Content</a>
              <a href="#termination" class="list-group-item list-group-item-action bg-transparent border-0 py-2 ps-3 text-secondary" @click.prevent="scrollTo('termination')">5. Termination</a>
              <a href="#liability" class="list-group-item list-group-item-action bg-transparent border-0 py-2 ps-3 text-secondary" @click.prevent="scrollTo('liability')">6. Limitation of Liability</a>
            </div>
          </div>
        </div>

        <div class="col-lg-9">

          <section id="acceptance" class="mb-5">
            <h3 class="fw-bold mb-3">1. Acceptance of Terms</h3>
            <p class="text-secondary">
              By accessing or using Anonymous Talk, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the Service. These Terms apply to all visitors, users, and others who access or use the Service.
            </p>
          </section>

          <section id="accounts" class="mb-5">
            <h3 class="fw-bold mb-3">2. Accounts & Identity</h3>
            <div class="card bg-body-tertiary border-0 p-4">
              <ul class="text-secondary mb-0">
                <li class="mb-2"><strong>Generated Identity:</strong> You acknowledge that your public identity (Username and Avatar) is generated by the platform to protect your privacy. You may not attempt to impersonate others or override these identifiers to mislead the community.</li>
                <li class="mb-2"><strong>Security:</strong> You are responsible for safeguarding the password that you use to access the Service. You agree not to disclose your password to any third party.</li>
                <li><strong>One Person, One Account:</strong> Creating multiple accounts to evade bans, manipulate Trust Scores, or harass users is strictly prohibited.</li>
              </ul>
            </div>
          </section>

          <section id="trust" class="mb-5">
            <h3 class="fw-bold mb-3">3. The Trust Score System</h3>
            <p class="text-secondary">
              Anonymous Talk utilizes an automated "Trust Score" system to maintain community health. You acknowledge and agree that:
            </p>
            <div class="alert alert-light border border-start-4 border-primary shadow-sm">
              <p class="mb-0 small text-muted">
                <strong>Feature Restriction:</strong> We reserve the right to automatically restrict your ability to Post or Comment if your Trust Score falls below certain thresholds (below 30% or 10%). These restrictions are automated based on community feedback (reports/likes).
              </p>
            </div>
            <p class="text-secondary small">
              We do not guarantee that your Trust Score will remain constant. It fluctuates based on your interactions and adherence to our Community Guidelines.
            </p>
          </section>

          <section id="content" class="mb-5">
            <h3 class="fw-bold mb-3">4. User Content</h3>
            <p class="text-secondary">
              Our Service allows you to post, link, store, share and otherwise make available certain information, text, graphics, videos, or other material ("Content"). You are responsible for the Content that you post to the Service, including its legality, reliability, and appropriateness.
            </p>
            <p class="text-secondary">
              By posting Content to the Service, you grant us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through the Service. You retain any and all of your rights to any Content you submit.
            </p>
          </section>

          <section id="termination" class="mb-5">
            <h3 class="fw-bold mb-3">5. Termination</h3>
            <p class="text-secondary">
              We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
            </p>
            <p class="text-secondary">
              Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service.
            </p>
          </section>

          <section id="liability" class="mb-5">
            <h3 class="fw-bold mb-3">6. Limitation of Liability</h3>
            <p class="text-secondary">
              In no event shall Anonymous Talk, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>
          </section>

          <div class="border-top pt-4">
            <p class="small text-muted">
              If you have any questions about these Terms, please contact us at <a href="#" class="text-decoration-none">legal@anonymoustalk.com</a>.
            </p>
          </div>

        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';

const lastUpdated = computed(() => {
  const date = new Date();
  return date.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
});

const scrollTo = (id) => {
  const element = document.getElementById(id);
  if (element) {
    element.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }
};
</script>

<style scoped>
.ls-1 {
  letter-spacing: 1px;
}

.list-group-item {
  font-size: 0.95rem;
  transition: all 0.2s ease;
  border-left: 2px solid transparent !important;
}

.list-group-item:hover {
  color: var(--bs-primary) !important;
  background-color: var(--bs-secondary-bg-subtle) !important;
  border-left: 2px solid var(--bs-primary) !important;
  padding-left: 1.5rem !important;
}
</style>
